import React from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  ArrowLeft, TrendingUp, Wallet, DollarSign, Users, Zap,
  ArrowRight, Shield, Clock, Sparkles, Target, BarChart3
} from 'lucide-react';
import ConnectButton from '../components/ConnectButton';

export default function Pool() {
  const navigate = useNavigate();

  const features = [
    { icon: TrendingUp, title: 'High Yield', description: 'Earn up to 3000% APY by providing liquidity to the community paymaster pool', color: 'emerald' },
    { icon: Shield, title: 'Fully Decentralized', description: 'No single point of failure. Community-owned gas fund powered by swap fees', color: 'cyan' },
    { icon: Clock, title: 'No Lock Period', description: 'Withdraw your USDC + earned yield anytime. Complete flexibility', color: 'violet' },
    { icon: Sparkles, title: '$ZEROTOLL Rewards', description: 'Earn bonus governance tokens for long-term liquidity provision', color: 'orange' }
  ];

  const stats = [
    { label: 'Current APY', value: '3,000%', color: 'text-emerald-400' },
    { label: 'Total Liquidity', value: '$1,000', color: 'text-cyan-400' },
    { label: 'Active Depositors', value: '42', color: 'text-violet-400' },
    { label: 'Fees Distributed', value: '$30K', color: 'text-orange-400' }
  ];

  return (
    <div className="min-h-screen bg-[#0a0a0f]">
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-cyan-500/10 rounded-full blur-[128px] animate-pulse" />
        <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-violet-500/10 rounded-full blur-[128px] animate-pulse" style={{ animationDelay: '1s' }} />
      </div>

      <header className="relative z-50 border-b border-white/10 backdrop-blur-xl bg-black/50">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <button onClick={() => navigate('/')} className="flex items-center gap-2 text-gray-400 hover:text-cyan-400 transition-colors">
            <ArrowLeft className="w-5 h-5" /><span className="font-medium">Back</span>
          </button>
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-cyan-500 to-violet-500 flex items-center justify-center">
              <Zap className="w-5 h-5 text-white" />
            </div>
            <span className="text-xl font-bold text-white">ZeroToll</span>
          </div>
          <ConnectButton />
        </div>
      </header>

      <main className="relative z-10 max-w-6xl mx-auto px-6 py-16">
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-cyan-500/10 border border-cyan-500/30 mb-6">
            <Wallet className="w-4 h-4 text-cyan-400" />
            <span className="text-sm text-cyan-400 font-medium">Liquidity Pools</span>
          </div>
          
          <h1 className="text-5xl md:text-6xl font-bold text-white mb-6">
            Earn While You<span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 via-violet-400 to-orange-400"> Fund Gas</span>
          </h1>
          
          <p className="text-xl text-gray-400 max-w-3xl mx-auto mb-8 leading-relaxed">
            Deposit USDC to the community paymaster pool and earn a share of all swap fees. 
            Help make DeFi gasless while earning high yields from protocol revenue.
          </p>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-12">
            {stats.map((stat, i) => (
              <div key={i} className="p-4 rounded-xl bg-white/5 border border-white/10 backdrop-blur-sm">
                <p className={`text-2xl font-bold ${stat.color} mb-1`}>{stat.value}</p>
                <p className="text-sm text-gray-500">{stat.label}</p>
              </div>
            ))}
          </div>

          <button onClick={() => navigate('/pool/dashboard')} className="inline-flex items-center gap-3 px-8 py-4 rounded-2xl bg-gradient-to-r from-cyan-500 to-violet-500 text-white font-semibold text-lg hover:shadow-2xl hover:shadow-cyan-500/25 hover:scale-105 transition-all duration-300">
            <BarChart3 className="w-5 h-5" />View Pool Dashboard<ArrowRight className="w-5 h-5" />
          </button>
        </div>

        {/* How It Works */}
        <div className="mb-16">
          <h2 className="text-3xl font-bold text-white text-center mb-12">How Liquidity Pools Work</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              { step: '01', title: 'Deposit USDC', description: 'Add your USDC to the community paymaster pool. No minimum amount required.', icon: Wallet },
              { step: '02', title: 'Earn from Fees', description: 'Receive 20% of all swap fees generated by the protocol. Fees are distributed automatically.', icon: DollarSign },
              { step: '03', title: 'Withdraw Anytime', description: 'No lock period. Withdraw your principal + earned yield whenever you want.', icon: Target }
            ].map((item, i) => (
              <div key={i} className="relative">
                <div className="p-6 rounded-2xl bg-white/5 border border-white/10 backdrop-blur-sm hover:bg-white/10 transition-all duration-300">
                  <div className="flex items-center gap-4 mb-4">
                    <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-cyan-500/20 to-violet-500/20 flex items-center justify-center">
                      <item.icon className="w-6 h-6 text-cyan-400" />
                    </div>
                    <span className="text-4xl font-bold text-white/20">{item.step}</span>
                  </div>
                  <h3 className="text-xl font-semibold text-white mb-3">{item.title}</h3>
                  <p className="text-gray-400 leading-relaxed">{item.description}</p>
                </div>
                {i < 2 && <div className="hidden md:block absolute top-1/2 -right-4 transform -translate-y-1/2"><ArrowRight className="w-8 h-8 text-gray-600" /></div>}
              </div>
            ))}
          </div>
        </div>

        {/* Features Grid */}
        <div className="mb-16">
          <h2 className="text-3xl font-bold text-white text-center mb-12">Why Choose ZeroToll Pools?</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {features.map((feature, i) => {
              const colorClasses = {
                emerald: 'from-emerald-500/20 to-emerald-500/5 border-emerald-500/30',
                cyan: 'from-cyan-500/20 to-cyan-500/5 border-cyan-500/30',
                violet: 'from-violet-500/20 to-violet-500/5 border-violet-500/30',
                orange: 'from-orange-500/20 to-orange-500/5 border-orange-500/30'
              };
              const iconColors = { emerald: 'text-emerald-400', cyan: 'text-cyan-400', violet: 'text-violet-400', orange: 'text-orange-400' };
              return (
                <div key={i} className={`p-6 rounded-2xl border bg-gradient-to-br ${colorClasses[feature.color]} backdrop-blur-sm hover:scale-105 transition-all duration-300`}>
                  <div className={`w-12 h-12 rounded-xl bg-white/10 flex items-center justify-center mb-4 ${iconColors[feature.color]}`}>
                    <feature.icon className="w-6 h-6" />
                  </div>
                  <h3 className="text-xl font-semibold text-white mb-3">{feature.title}</h3>
                  <p className="text-gray-400 leading-relaxed">{feature.description}</p>
                </div>
              );
            })}
          </div>
        </div>

        {/* CTA Section */}
        <div className="text-center p-12 rounded-3xl bg-gradient-to-r from-cyan-500/10 via-violet-500/10 to-orange-500/10 border border-white/10 backdrop-blur-sm">
          <h2 className="text-3xl font-bold text-white mb-4">Ready to Start Earning?</h2>
          <p className="text-gray-400 mb-8 max-w-2xl mx-auto">Join the community of liquidity providers earning high yields while making DeFi more accessible for everyone.</p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button onClick={() => navigate('/pool/dashboard')} className="inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-gradient-to-r from-cyan-500 to-violet-500 text-white font-semibold hover:shadow-lg hover:shadow-cyan-500/25 transition-all">
              <BarChart3 className="w-5 h-5" />View Dashboard
            </button>
            <button onClick={() => navigate('/swap')} className="inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-white/10 text-white font-semibold hover:bg-white/20 transition-all">
              <Zap className="w-5 h-5" />Try Gasless Swaps
            </button>
          </div>
        </div>
      </main>

      <footer className="relative z-10 border-t border-white/10 py-8 mt-16">
        <div className="max-w-6xl mx-auto px-6 text-center text-sm text-gray-500">
          <p>© 2025 ZeroToll. Making DeFi gasless for everyone.</p>
        </div>
      </footer>
    </div>
  );
}
